// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamingCatalogue.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamingCatalogue.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GameplayScore")
                        .HasColumnType("float");

                    b.Property<double>("GraphicsScore")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MusicScore")
                        .HasColumnType("float");

                    b.Property<double>("StoryScore")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Вы- ведьмак Геральт из Ривии. Убийца чудовищ, путешествующий по миру, в котором бушует война. Спасите Цири - Дитя Предназначения, живое оружие, способное спасти или уничтожить мир. Из двух зол сумейте выбрать меньшее",
                            GameplayScore = 9.0,
                            GraphicsScore = 8.5,
                            ImageUrl = "https://avatars.mds.yandex.net/i?id=e27a86862375d4e411a2fd746c50637e32718eb5-4571389-images-thumbs&n=13",
                            MusicScore = 10.0,
                            StoryScore = 9.1999999999999993,
                            Title = "The Witcher 3",
                            Year = "2015"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Доброе утро, Найт-сити! Сыграйте за наемника Ви, пытающегося выжить в городе будущего, где выше всего ценятся деньги",
                            GameplayScore = 8.5,
                            GraphicsScore = 10.0,
                            ImageUrl = "https://avatars.mds.yandex.net/i?id=5c320c7935e0c26be3a814ee8d5d0d0b8ab4e6a6-6489204-images-thumbs&n=13",
                            MusicScore = 10.0,
                            StoryScore = 9.5,
                            Title = "Cyberpunk 2077",
                            Year = "2020"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
